"""add contactos table

Revision ID: 54699d21e348
Revises: a1b2c3d4e5f6
Create Date: 2026-05-09 13:56:35.003968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54699d21e348'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
